sudo: false
language: node_js
node_js:
  - 10
  - 12
  - 14
after_success:
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
notifications:
  slack:
    secure: PSCuDMpkIy5Pu9cAIhrEmMrHGp+WZDdrD6pcXu2yiqhn+UDW5DwYebf35CsL+ieQSxBQSY51HV9Z5xYkz2LhNediAzkqLRKMHBbt+P1JsTQy3YO9xKShkLGjdvEwJlaC2l/RpiWYvKl79xljtAndknC9lywcEr+uxzj//E2+LIMRlSt3307RWWE5fOqk1VbnuRXEqPQnq7zRtgP/f22hVBzS3FMe+sYP2bVZgagfXeYxq2dePrDofjuRLBmzLPrw9eTuI0px1mFnOJixHq0qPpNDLW7c54BWCjy0IxFGbvyUWmk+4LdDOKcGAVVOEr5F5S02+1js5mfljQdThEfRp44UfGrKfo6HOvXN46ORyYAMVRpNLevOzdp9ABAL1037CttPGyYYY90PanTxhdsceeIqNXewhjjjNCH12ST8s/JFV8bE7i8vODDPKUhzqdRbrQt0q84QlHIU2zIY+5eyOTxRCznBYEhX8cRSfNGjhnMnz3ma9uffsUDJpZ3ZNc8eEvkDvmduli877SRsy0Igf7Sk6pEUVd5WRHeom77Zte2VftPcVot8YcLzkD7UxWqlLFn6VDtRqYc8u7ruv2XVhWFUA9wu5wBXqOMsqJqRTJAl6NpO2byi/z9QI1HEChRurUtofXXhzzrX1ENs8S42efFt1EWdNBNK4Taa+xApZ28=
